data:
    dataset: "CIFAR10"
    image_size: 38
    channels: 64
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 4

model:
    type: "simple"
    input_size : 32
    in_channels: 3
    out_ch: 25
    ch: 32
    ch_mult: [2, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: [8,4]
    dropout: 0.2
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 500

training:
    batch_size: 256
    n_epochs: 100
    n_iters: 5000000
    snapshot_freq: 1000
    validation_freq: 2000

sampling:
    batch_size: 64
    last_only: True

optim:
    weight_decay: 0.0001
    optimizer: "AdamW"
    lr: 0.0002
    lr2: 0.001
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0

unet:
    type: "simple"
    in_channels: 3
    out_ch: 64
    ch: 128
    ch_mult: [1, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: [32, 16, 8, 4, 1]
    dropout: 0.2
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True